In [26]:
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile
import glob
import os
import re

In [69]:
path = r'C:\Users\benny\OneDrive\Machine Learning\ML1030\Final Project\Final Project\Data' # use your path
all_csv_files = glob.glob(os.path.join(path, "*.csv"))
all_xlsx_files = glob.glob(os.path.join(path, "*.xlsx"))

#(head, tail) = os.path.split(all_xlsx_files[0])
#print(tail)
#name = re.search('(.+?).xlsx', tail).group(1)
#print(name)
#data_xls = pd.read_excel(all_xlsx_files[0])
#data_xls.to_csv(name+'.csv', encoding='utf-8')

#for filename in all_xlsx_files[0:1]:
#    data_xls = pd.read_excel(filename, 'Sheet2', index_col=None)
#    data_xls.to_csv('csvfile.csv', encoding='utf-8')

print(len(all_csv_files))
print(len(all_xlsx_files))

76
101

In [80]:
li_csv = pd.DataFrame()
i = 1

for filename in all_csv_files:
    (head, tail) = os.path.split(filename)
    teams = re.search('NFL-(.+?)-data', tail).group(1)
    #print(tail)
    #print(teams)
    away=teams.split('@')[0]
    home=teams.split('@')[1]
    #print(away)
    #print(home)
    csv_df = pd.read_csv(filename)
    csv_df['Away'] = away
    csv_df['Home'] = home
    csv_df['Game'] = teams
    csv_df['Game Number'] = i
    i = i+1
    li_csv = pd.concat([li_csv,csv_df],sort=None)

print(li_csv.shape)    
    
li_xlsx = pd.DataFrame()

for filename in all_xlsx_files:
    (head, tail) = os.path.split(filename)
    teams = re.search('NFL-(.+?)-data', tail).group(1)
    #print(tail)
    #print(teams)
    away=teams.split('@')[0]
    home=teams.split('@')[1]
    #print(away)
    #print(home)
    xlsx_df = pd.read_excel(filename)
    xlsx_df['Away'] = away
    xlsx_df['Home'] = home
    xlsx_df['Game'] = teams
    xlsx_df['Game Number'] = i
    i = i+1
    li_xlsx = pd.concat([li_xlsx,xlsx_df],sort=None)

print(li_xlsx.shape)

all_data = pd.concat([li_csv,li_xlsx], sort=None, ignore_index=True)

print(all_data)
all_data.to_csv(path+"\\all_data.csv")

(288386, 15)
(128950, 15)
                                           Date       Book Away Moneyline  \
0       Sun Sep 02 2018 15:37:47 GMT+0000 (UTC)   AlfaBook            115
1       Thu Aug 30 2018 20:54:20 GMT+0000 (UTC)  BravoBook            NaN
2       Thu Aug 30 2018 21:54:19 GMT+0000 (UTC)  BravoBook            NaN
3       Thu Aug 30 2018 22:54:20 GMT+0000 (UTC)  BravoBook            NaN
4       Thu Aug 30 2018 23:54:20 GMT+0000 (UTC)  BravoBook            NaN
5       Fri Aug 31 2018 00:54:20 GMT+0000 (UTC)  BravoBook            NaN
6       Fri Aug 31 2018 13:54:19 GMT+0000 (UTC)  BravoBook            NaN
7       Fri Aug 31 2018 14:54:19 GMT+0000 (UTC)  BravoBook            NaN
8       Fri Aug 31 2018 15:54:20 GMT+0000 (UTC)  BravoBook            NaN
9       Fri Aug 31 2018 16:54:21 GMT+0000 (UTC)  BravoBook            NaN
10      Fri Aug 31 2018 17:54:20 GMT+0000 (UTC)  BravoBook            NaN
11      Fri Aug 31 2018 18:54:20 GMT+0000 (UTC)  BravoBook            NaN
12      Fri Aug 31 2018 19:54:19 GMT+0000 (UTC)  BravoBook            130
13      Fri Aug 31 2018 20:54:20 GMT+0000 (UTC)  BravoBook            130
14      Fri Aug 31 2018 21:54:20 GMT+0000 (UTC)  BravoBook            130
15      Fri Aug 31 2018 22:54:20 GMT+0000 (UTC)  BravoBook            130
16      Fri Aug 31 2018 23:54:21 GMT+0000 (UTC)  BravoBook            130
17      Sat Sep 01 2018 00:54:20 GMT+0000 (UTC)  BravoBook            130
18      Sat Sep 01 2018 01:54:20 GMT+0000 (UTC)  BravoBook            130
19      Sat Sep 01 2018 02:54:20 GMT+0000 (UTC)  BravoBook            130
20      Sat Sep 01 2018 03:54:19 GMT+0000 (UTC)  BravoBook            130
21      Sat Sep 01 2018 04:54:19 GMT+0000 (UTC)  BravoBook            130
22      Sat Sep 01 2018 05:54:19 GMT+0000 (UTC)  BravoBook            130
23      Sat Sep 01 2018 06:54:19 GMT+0000 (UTC)  BravoBook            130
24      Sat Sep 01 2018 07:54:19 GMT+0000 (UTC)  BravoBook            130
25      Sat Sep 01 2018 08:54:19 GMT+0000 (UTC)  BravoBook            130
26      Sat Sep 01 2018 09:54:19 GMT+0000 (UTC)  BravoBook            130
27      Sat Sep 01 2018 10:54:19 GMT+0000 (UTC)  BravoBook            130
28      Sat Sep 01 2018 11:54:19 GMT+0000 (UTC)  BravoBook            130
29      Sat Sep 01 2018 12:54:19 GMT+0000 (UTC)  BravoBook            130
...                                         ...        ...            ...
417306  Sat Dec 29 2018 16:25:45 GMT+0000 (UTC)   AlfaBook            385
417307  Sat Dec 29 2018 17:26:17 GMT+0000 (UTC)   AlfaBook            385
417308  Sat Dec 29 2018 18:25:30 GMT+0000 (UTC)   AlfaBook            385
417309  Sat Dec 29 2018 19:26:03 GMT+0000 (UTC)   AlfaBook            385
417310  Sat Dec 29 2018 20:25:36 GMT+0000 (UTC)   AlfaBook            385
417311  Sat Dec 29 2018 21:25:43 GMT+0000 (UTC)   AlfaBook            385
417312  Sat Dec 29 2018 22:25:59 GMT+0000 (UTC)   AlfaBook            385
417313  Sat Dec 29 2018 23:25:39 GMT+0000 (UTC)   AlfaBook            385
417314  Sun Dec 30 2018 00:25:44 GMT+0000 (UTC)   AlfaBook            385
417315  Sun Dec 30 2018 01:26:05 GMT+0000 (UTC)   AlfaBook            385
417316  Sun Dec 30 2018 02:25:49 GMT+0000 (UTC)   AlfaBook            385
417317  Sun Dec 30 2018 03:25:54 GMT+0000 (UTC)   AlfaBook            385
417318  Sun Dec 30 2018 04:26:06 GMT+0000 (UTC)   AlfaBook            385
417319  Sun Dec 30 2018 05:25:43 GMT+0000 (UTC)   AlfaBook            385
417320  Sun Dec 30 2018 06:25:34 GMT+0000 (UTC)   AlfaBook            385
417321  Sun Dec 30 2018 07:25:09 GMT+0000 (UTC)   AlfaBook            385
417322  Sun Dec 30 2018 08:25:44 GMT+0000 (UTC)   AlfaBook            385
417323  Sun Dec 30 2018 09:26:28 GMT+0000 (UTC)   AlfaBook            385
417324  Sun Dec 30 2018 10:25:50 GMT+0000 (UTC)   AlfaBook            385
417325  Sun Dec 30 2018 11:25:18 GMT+0000 (UTC)   AlfaBook            385
417326  Sun Dec 30 2018 12:25:46 GMT+0000 (UTC)   AlfaBook            385
417327  Sun Dec 30 2018 13:26:01 GMT+0000 (UTC)   AlfaBook            385
417328  Sun Dec 30 2018 14:25:44 GMT+0000 (UTC)   AlfaBook            385
417329  Sun Dec 30 2018 15:26:16 GMT+0000 (UTC)   AlfaBook            405
417330  Sun Dec 30 2018 16:26:05 GMT+0000 (UTC)   AlfaBook            405
417331  Sun Dec 30 2018 17:25:41 GMT+0000 (UTC)   AlfaBook            405
417332  Sun Dec 30 2018 18:24:41 GMT+0000 (UTC)   AlfaBook            360
417333  Sun Dec 30 2018 19:24:49 GMT+0000 (UTC)   AlfaBook            360
417334  Sun Dec 30 2018 20:24:51 GMT+0000 (UTC)   AlfaBook            360
417335  Sun Dec 30 2018 21:24:56 GMT+0000 (UTC)   AlfaBook            395

       Home Moneyline Away Pointspread points  Away Pointspread odds  \
0                -135                     2.5                 -110.0
1                 NaN                       3                 -119.0
2                 NaN                       3                 -110.0
3                 NaN                       3                 -110.0
4                 NaN                       3                 -110.0
5                 NaN                       3                 -110.0
6                 NaN                       3                 -119.0
7                 NaN                       3                 -119.0
8                 NaN                       3                 -119.0
9                 NaN                       3                 -119.0
10                NaN                       3                 -119.0
11                NaN                       3                 -119.0
12               -150                       3                 -119.0
13               -150                       3                 -119.0
14               -150                       3                 -119.0
15               -150                       3                 -119.0
16               -150                       3                 -119.0
17               -150                       3                 -119.0
18               -150                       3                 -119.0
19               -150                       3                 -119.0
20               -150                       3                 -119.0
21               -150                       3                 -119.0
22               -150                       3                 -115.0
23               -150                       3                 -115.0
24               -150                       3                 -115.0
25               -150                       3                 -115.0
26               -150                       3                 -115.0
27               -150                       3                 -115.0
28               -150                       3                 -115.0
29               -150                       3                 -115.0
...               ...                     ...                    ...
417306           -460                      10                 -110.0
417307           -460                      10                 -104.0
417308           -460                      10                 -104.0
417309           -460                      10                 -104.0
417310           -460                      10                 -104.0
417311           -460                      10                 -104.0
417312           -460                      10                 -104.0
417313           -460                      10                 -104.0
417314           -460                      10                 -104.0
417315           -460                      10                 -104.0
417316           -460                      10                 -104.0
417317           -460                      10                 -104.0
417318           -460                      10                 -104.0
417319           -460                      10                 -104.0
417320           -460                    10.5                 -110.0
417321           -460                    10.5                 -108.0
417322           -460                    10.5                 -108.0
417323           -460                    10.5                 -108.0
417324           -460                    10.5                 -108.0
417325           -460                    10.5                 -108.0
417326           -460                    10.5                 -108.0
417327           -460                    10.5                 -108.0
417328           -460                    10.5                 -108.0
417329           -500                    10.5                 -108.0
417330           -500                    10.5                 -108.0
417331           -500                    10.5                 -108.0
417332           -430                    10.5                 -110.0
417333           -430                    10.5                 -110.0
417334           -430                    10.5                 -110.0
417335           -470                    10.5                 -110.0

       Home Pointspread points  Home Pointspread odds  Total points  \
0                         -2.5                 -110.0          45.5
1                           -3                 -101.0          45.5
2                           -3                 -110.0          45.5
3                           -3                 -110.0          45.5
4                           -3                 -110.0          45.5
5                           -3                 -110.0          45.5
6                           -3                 -101.0          45.5
7                           -3                 -101.0          45.5
8                           -3                 -101.0          45.5
9                           -3                 -101.0          45.5
10                          -3                 -101.0          45.5
11                          -3                 -101.0          45.5
12                          -3                 -101.0          45.5
13                          -3                 -101.0          45.5
14                          -3                 -101.0          45.5
15                          -3                 -101.0          45.5
16                          -3                 -101.0          45.5
17                          -3                 -101.0          45.5
18                          -3                 -101.0          45.5
19                          -3                 -101.0          45.5
20                          -3                 -101.0          45.5
21                          -3                 -101.0          45.5
22                          -3                 -105.0          45.5
23                          -3                 -105.0          45.5
24                          -3                 -105.0          45.5
25                          -3                 -105.0          45.5
26                          -3                 -105.0          45.5
27                          -3                 -105.0          45.5
28                          -3                 -105.0          45.5
29                          -3                 -105.0          45.5
...                        ...                    ...           ...
417306                     -10                 -110.0          48.5
417307                     -10                 -116.0          48.5
417308                     -10                 -116.0          48.5
417309                     -10                 -116.0          48.5
417310                     -10                 -116.0          48.5
417311                     -10                 -116.0          48.5
417312                     -10                 -116.0          48.5
417313                     -10                 -116.0          48.5
417314                     -10                 -116.0          48.5
417315                     -10                 -116.0          48.5
417316                     -10                 -116.0          48.5
417317                     -10                 -116.0          48.5
417318                     -10                 -116.0          48.5
417319                     -10                 -116.0          48.5
417320                   -10.5                 -110.0          48.5
417321                   -10.5                 -112.0          48.5
417322                   -10.5                 -112.0          48.5
417323                   -10.5                 -112.0          48.5
417324                   -10.5                 -112.0          48.5
417325                   -10.5                 -112.0          48.5
417326                   -10.5                 -112.0          48.5
417327                   -10.5                 -112.0          48.5
417328                   -10.5                 -112.0          48.5
417329                   -10.5                 -112.0          48.5
417330                   -10.5                 -112.0          49.0
417331                   -10.5                 -112.0          49.0
417332                   -10.5                 -110.0          49.0
417333                   -10.5                 -110.0          49.0
417334                   -10.5                 -110.0          49.0
417335                   -10.5                 -110.0          50.0

        Over odds  Under odds Away Home     Game  Game Number
0          -108.0      -112.0  ATL  PHI  ATL@PHI            1
1          -105.0      -115.0  ATL  PHI  ATL@PHI            1
2          -105.0      -115.0  ATL  PHI  ATL@PHI            1
3          -105.0      -115.0  ATL  PHI  ATL@PHI            1
4          -105.0      -115.0  ATL  PHI  ATL@PHI            1
5          -105.0      -115.0  ATL  PHI  ATL@PHI            1
6          -105.0      -115.0  ATL  PHI  ATL@PHI            1
7          -105.0      -115.0  ATL  PHI  ATL@PHI            1
8          -105.0      -115.0  ATL  PHI  ATL@PHI            1
9          -105.0      -115.0  ATL  PHI  ATL@PHI            1
10         -105.0      -115.0  ATL  PHI  ATL@PHI            1
11         -105.0      -115.0  ATL  PHI  ATL@PHI            1
12         -105.0      -115.0  ATL  PHI  ATL@PHI            1
13         -105.0      -115.0  ATL  PHI  ATL@PHI            1
14         -105.0      -115.0  ATL  PHI  ATL@PHI            1
15         -105.0      -115.0  ATL  PHI  ATL@PHI            1
16         -105.0      -115.0  ATL  PHI  ATL@PHI            1
17         -105.0      -115.0  ATL  PHI  ATL@PHI            1
18         -105.0      -115.0  ATL  PHI  ATL@PHI            1
19         -105.0      -115.0  ATL  PHI  ATL@PHI            1
20         -105.0      -115.0  ATL  PHI  ATL@PHI            1
21         -105.0      -115.0  ATL  PHI  ATL@PHI            1
22         -105.0      -115.0  ATL  PHI  ATL@PHI            1
23         -105.0      -115.0  ATL  PHI  ATL@PHI            1
24         -105.0      -115.0  ATL  PHI  ATL@PHI            1
25         -105.0      -115.0  ATL  PHI  ATL@PHI            1
26         -105.0      -115.0  ATL  PHI  ATL@PHI            1
27         -105.0      -115.0  ATL  PHI  ATL@PHI            1
28         -105.0      -115.0  ATL  PHI  ATL@PHI            1
29         -105.0      -115.0  ATL  PHI  ATL@PHI            1
...           ...         ...  ...  ...      ...          ...
417306     -108.0      -112.0   SF  LAR   SF@LAR          177
417307     -108.0      -112.0   SF  LAR   SF@LAR          177
417308     -108.0      -112.0   SF  LAR   SF@LAR          177
417309     -108.0      -112.0   SF  LAR   SF@LAR          177
417310     -108.0      -112.0   SF  LAR   SF@LAR          177
417311     -108.0      -112.0   SF  LAR   SF@LAR          177
417312     -108.0      -112.0   SF  LAR   SF@LAR          177
417313     -108.0      -112.0   SF  LAR   SF@LAR          177
417314     -108.0      -112.0   SF  LAR   SF@LAR          177
417315     -108.0      -112.0   SF  LAR   SF@LAR          177
417316     -108.0      -112.0   SF  LAR   SF@LAR          177
417317     -108.0      -112.0   SF  LAR   SF@LAR          177
417318     -108.0      -112.0   SF  LAR   SF@LAR          177
417319     -108.0      -112.0   SF  LAR   SF@LAR          177
417320     -108.0      -112.0   SF  LAR   SF@LAR          177
417321     -108.0      -112.0   SF  LAR   SF@LAR          177
417322     -108.0      -112.0   SF  LAR   SF@LAR          177
417323     -108.0      -112.0   SF  LAR   SF@LAR          177
417324     -108.0      -112.0   SF  LAR   SF@LAR          177
417325     -108.0      -112.0   SF  LAR   SF@LAR          177
417326     -108.0      -112.0   SF  LAR   SF@LAR          177
417327     -108.0      -112.0   SF  LAR   SF@LAR          177
417328     -108.0      -112.0   SF  LAR   SF@LAR          177
417329     -108.0      -112.0   SF  LAR   SF@LAR          177
417330     -111.0      -109.0   SF  LAR   SF@LAR          177
417331     -115.0      -105.0   SF  LAR   SF@LAR          177
417332     -115.0      -105.0   SF  LAR   SF@LAR          177
417333     -115.0      -105.0   SF  LAR   SF@LAR          177
417334     -115.0      -105.0   SF  LAR   SF@LAR          177
417335     -110.0      -110.0   SF  LAR   SF@LAR          177

[417336 rows x 15 columns]

In [81]:
all_data.head()

,Date,Book,Away Moneyline,Home Moneyline,Away Pointspread points,Away Pointspread odds,Home Pointspread points,Home Pointspread odds,Total points,Over odds,Under odds,Away,Home,Game,Game Number
0,Sun Sep 02 2018 15:37:47 GMT+0000 (UTC),AlfaBook,115,-135,2.5,-110.0,-2.5,-110.0,45.5,-108.0,-112.0,ATL,PHI,ATL@PHI,1
1,Thu Aug 30 2018 20:54:20 GMT+0000 (UTC),BravoBook,NaN,NaN,3,-119.0,-3,-101.0,45.5,-105.0,-115.0,ATL,PHI,ATL@PHI,1
2,Thu Aug 30 2018 21:54:19 GMT+0000 (UTC),BravoBook,NaN,NaN,3,-110.0,-3,-110.0,45.5,-105.0,-115.0,ATL,PHI,ATL@PHI,1
3,Thu Aug 30 2018 22:54:20 GMT+0000 (UTC),BravoBook,NaN,NaN,3,-110.0,-3,-110.0,45.5,-105.0,-115.0,ATL,PHI,ATL@PHI,1
4,Thu Aug 30 2018 23:54:20 GMT+0000 (UTC),BravoBook,NaN,NaN,3,-110.0,-3,-110.0,45.5,-105.0,-115.0,ATL,PHI,ATL@PHI,1

In [16]:
raw_xlsx_data.head()

,Date,Book,Away Moneyline,Home Moneyline,Away Pointspread points,Away Pointspread odds,Home Pointspread points,Home Pointspread odds,Total points,Over odds,Under odds
0,Mon Sep 17 2018 04:43:33 GMT+0000 (UTC),IndiaBook,140,-165,3,-110.0,-3,-110.0,39.5,-110.0,-110.0
1,Mon Sep 17 2018 05:43:35 GMT+0000 (UTC),IndiaBook,140,-165,3,-110.0,-3,-110.0,39.5,-110.0,-110.0
2,Mon Sep 17 2018 06:43:35 GMT+0000 (UTC),IndiaBook,140,-165,3,-110.0,-3,-110.0,39.5,-110.0,-110.0
3,Mon Sep 17 2018 07:43:35 GMT+0000 (UTC),IndiaBook,140,-165,3,-110.0,-3,-110.0,39.5,-110.0,-110.0
4,Mon Sep 17 2018 08:43:35 GMT+0000 (UTC),IndiaBook,140,-165,3,-110.0,-3,-110.0,39.5,-110.0,-110.0

In [14]:
import datetime
datee = datetime.datetime.strptime(raw_data.Date, "%Y-%m-%d")

TypeError: strptime() argument 1 must be str, not Series