In [31]:
import pandas as pd
import numpy as np
from datetime import datetime
from pytz import timezone
import pytz
import glob
import os
import re

In [32]:
nfl_games_file = r'C:\Users\benny\OneDrive\Machine Learning\ML1030\Final Project\Final Project\sportsbook_data_ALL.csv'
nfl_games_df = pd.read_csv(nfl_games_file)

In [33]:
nfl_games_df.head()

,Unnamed: 0,Date_x,Book,Away Moneyline,Home Moneyline,Away Pointspread points,Away Pointspread odds,Home Pointspread points,Home Pointspread odds,Total points,...,YdsW,TOW,YdsL,TOL,Home_y,Home_abbr,Away_y,Away_abbr,Game Time,Pre-Game
0,0,Sun Sep 02 2018 15:37:47 GMT+0000 (UTC),AlfaBook,115,-135,2.5,-110.0,-2.5,-110.0,45.5,...,232,2,299,1,Philadelphia Eagles,PHI,Atlanta Falcons,ATL,2018-09-06 20:20:00-04:00,True
1,1,Thu Aug 30 2018 20:54:20 GMT+0000 (UTC),BravoBook,NaN,NaN,3,-119.0,-3,-101.0,45.5,...,232,2,299,1,Philadelphia Eagles,PHI,Atlanta Falcons,ATL,2018-09-06 20:20:00-04:00,True
2,2,Thu Aug 30 2018 21:54:19 GMT+0000 (UTC),BravoBook,NaN,NaN,3,-110.0,-3,-110.0,45.5,...,232,2,299,1,Philadelphia Eagles,PHI,Atlanta Falcons,ATL,2018-09-06 20:20:00-04:00,True
3,3,Thu Aug 30 2018 22:54:20 GMT+0000 (UTC),BravoBook,NaN,NaN,3,-110.0,-3,-110.0,45.5,...,232,2,299,1,Philadelphia Eagles,PHI,Atlanta Falcons,ATL,2018-09-06 20:20:00-04:00,True
4,4,Thu Aug 30 2018 23:54:20 GMT+0000 (UTC),BravoBook,NaN,NaN,3,-110.0,-3,-110.0,45.5,...,232,2,299,1,Philadelphia Eagles,PHI,Atlanta Falcons,ATL,2018-09-06 20:20:00-04:00,True

In [40]:
def calculate_juice(away,home):
  if(away < 0):
    decimal_odds_away = 1+100/abs(away)
  else:
    decimal_odds_away = 1+abs(away)/100

  if(home < 0):
    decimal_odds_home = 1+100/abs(home)
  else:
    decimal_odds_home = 1+abs(home)/100
    
  return (1-(decimal_odds_away*decimal_odds_home)/(decimal_odds_away+decimal_odds_home))*100

In [52]:
#x = calculate_juice(325,-435)

#x = nfl_games_df['Away Moneyline'].apply(lambda x: type(x)==float)

#nfl_games_df["Home Moneyline"] = pd.to_numeric(nfl_games_df["Home Moneyline"])

for index, row in nfl_games_df.iterrows():
    if index == 5:
        break
    #print(type(row['Away Moneyline']))
    print(type(row['Home Moneyline']))

<class 'str'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>

In [42]:
print(x)

4.614577871001579